#!/bin/bash

# Clone the latest pre-commit hook script from GitHub
GITHUB_REPO_URL="https://github.com/OpenSemanticLab/interactive-semantic-graph.git"
HOOK_SCRIPT="pre-commit"

# Remove the existing pre-commit script (optional)
rm -f .git/hooks/pre-commit

# Clone the pre-commit script from GitHub
curl -sSfL "$GITHUB_REPO_URL/$HOOK_SCRIPT" -o .git/hooks/pre-commit || {
    echo "Failed to clone the pre-commit hook from GitHub."
    exit 1
}

# Make the hook script executable
chmod +x .git/hooks/pre-commit

# Run npm test
echo "Running npm test..."
npm test

# Check for ESLint errors
echo "Running ESLint..."
npm run eslint

# Check the exit codes of the previous commands
if [ $? -eq 0 ]; then
    exit 0 # Commit allowed
else
    echo "ERROR: Commit aborted due to failing tests or ESLint errors. Please fix the issues and try again."
    exit 1 # Commit blocked
fi
